[package]
name = "trophy-wife"
version = "0.1.0"
authors = ["Krittin Meenrattanakorn <whatevermarch@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11.1"
winit = "0.19.1"
vulkano-win = "0.11.1"
